### ISSUE TITLE
Object [object Object] has no method 'attachSchema'

### ISSUE THREAD

**Issue by jjman505** [zimme/meteor-collection-softremovable#17]
I'm getting an error.

Here's the output of `meteor list`: https://gist.github.com/jjman505/9f5a2773271d72daa35d

And here's the file in question: https://gist.github.com/jjman505/6a4c200f7a32e10e5abb

```
TypeError: Object [object Object] has no method 'attachSchema'
     at Object.behaviour (packages/zimme:collection-softremovable/softremovable.coffee:81:17)
     at [object Object].share.attach.attach (packages/zimme:collection-behaviours/collection-behaviours.coffee:13:15)
     at [object Object].Mongo.Collection.attachBehaviour (packages/zimme:collection-behaviours/mongo.coffee:4:10)
     at app/lib/collections/iddocs.js:4:8
     at app/lib/collections/iddocs.js:65:3
     at /home/jeremy/Code/iohk-enrollment/attainenroll/.meteor/local/build/programs/server/boot.js:222:10
     at Array.forEach (native)
     at Function._.each._.forEach (/home/jeremy/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /home/jeremy/Code/iohk-enrollment/attainenroll/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by zimme** [comment]
Hey, yeah. This Happens when you use this package together with simple-schema without collection2. I've fixed this in timestampable but forgot to fix it in this package. I'll try my best to fix it this weekend, otherwise i'll carve out some time on monday.

**Comment by jjman505** [comment]
Okay, thanks. For now, I'll just see if I can add collection2.

**Comment by zimme** [comment]
`1.0.5` published.
